#!/bin/bash

echo
echo "****************************************************"
echo "This script will delete all the data on the project!"
echo "****************************************************"
echo

read -p "Are you sure you want to continue? (yes/no) "
if [ "$REPLY" != "yes" ]; then
   exit
fi
echo

echo "Deleting virtual environment (myvenv) ..."
rm -rf myvenv/
echo "Done"

echo "Deleting data folder (data) ..."
rm -rf data/
echo "Done"

echo "Deleting media folder (media) ..."
rm -rf media/
echo "Done"

echo "Environment Clean!"
