# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textmeh', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='translation',
            field=models.CharField(default='test', max_length=5000),
            preserve_default=False,
        ),
    ]
