# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textmeh', '0003_chat_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='language',
            field=models.CharField(max_length=2),
        ),
    ]
